// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcqebhrxqypckbshlznw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjcWViaHJ4cXlwY2tic2hsem53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4Njc4NzUsImV4cCI6MjA3ODQ0Mzg3NX0.MoQFoouGdXBW5amqXS8Usq86KpbOIRYUQjSBsLgYPzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});